# Example serve.json configuration:
# {
#   "https": {
#     "python.homecloud": {
#       "handler": {
#         "proxy": "http://localhost:8000"
#       }
#     }
#   }
# }

name: python-server
services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    hostname: python
    cap_add:
      - net_admin
      - sys_module
    environment:
      - TS_AUTHKEY=${TS_CLIENT_SECRET}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container --reset
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/serve.json
    volumes:
      - ./.runtime/tailscale/:/var/lib/tailscale/
      - ./config/tailscale/:/config/
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

  python-server:
    image: python:3.11-slim
    container_name: python_server
    volumes:
      - ./www:/srv/www
    network_mode: "service:tailscale"
    restart: unless-stopped
    working_dir: /srv/www
    command: python -m http.server 8000

